build: Convert `OneSignalInAppMessagesMocks` to group
* ❗️ After `OneSignalInAppMessagesMocks` was created, I had to then manually choose this folder and "Convert to Group" or else the CI had build errors about the following:

xcodebuild: error: Unable to read project 'OneSignal.xcodeproj'
Reason: The project ‘OneSignal’ is damaged and cannot be opened. Examine the project file for invalid edits or unresolved source control conflicts.
Exception: didn't find classname for 'isa' key