chore(tests): Add in app messaging testing infrastructure and tests (#1615)
* chore(tests): Add Swift `IAMIntegrationTests` file

Add Swift `IAMIntegrationTests` test file and check for accessibility of `OSMessagingController` from the test file

* nit: remove unused methods `getTriggerValueForKey`

* no longer used, dead code

* nit: remove methods from OSMessagingController header

* Aren't called by anything so no need to be on the interface, these are called by the class itself.

* Add description to `OSRequestGetInAppMessages`

* Without a description, the object will return something like `<OSRequestGetInAppMessages: 0x600001798bc0>`. By adding a predictable description, we can operate on the object.

* chore(tests): Add framework for OneSignalInAppMessagesMocks

* Re-usable test helpers and mock functionality
* Include own swiftlint file
* ❗️ After `OneSignalInAppMessagesMocks` was created, I had to then manually "convert to group" or else the CI had build errors about the following:

xcodebuild: error: Unable to read project 'OneSignal.xcodeproj'
Reason: The project ‘OneSignal’ is damaged and cannot be opened. Examine the project file for invalid edits or unresolved source control conflicts.
Exception: didn't find classname for 'isa' key

* chore(tests): move `UIApplication+OneSignal` from OneSIgnal > OneSignalInAppMessages

* This extension on `UIApplication` is only used in the `OneSignalInAppMessages` framework, so there is no need to keep it in the umbrella `OneSignalFramework` framework, which causes errors if only `OneSignalInAppMessages` is tested (without also importing OneSignalFramework).

* chore(tests): Add ConsistencyManagerTestHelpers to tests

* Has helper methods for repeating functionality

* Add / migrate some existing IAM integration tests

* Attempt to migrate `testDisablingIAMs_stillCreatesMessageQueue_butPreventsMessageDisplay` to new tests, but behavior has changed. It becomes `testPausingIAMs_doesNotCreateMessageQueue`
* Migrate `testPreviewIAMIsDisplayedOnPause`

* address PR feedback

* `messageViewImpressionRequest` was removed from the `OSMessagingController` header file, so update `OSMessagingControllerOverrider` to expose it for internal usage.
* Delete old tests that have been migrated